# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: b756cd2c6afcdf0b1cffdba38380722b10dbff8ed71b9bba3e82358cb41ef562e2f4233844d1152f79f1e8a21bf7e3785f6f64813432f6ade546b65bf2127d6a

test:
  secret_key_base: 9cd9f386e3ffa1ac4efc228ca80be6633c53cde68d5c566016ef35583038f3472813ddbafc4dc25646ef37d7d4af1a4da45d3cd4b79653510c080515c615124a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
